---
baseURL: "./"
languageCode: en-us
Title: Matúš Solčány
theme:
  - hugo-video
  - matussolcany

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    Author: Matúš Solčány
    Description: The portfolio of digital designer and developer Matus Solcany
    titleShort: Matúš Solčány
    homeGridColumns: 3
    projectCategories:
    - visual
    - interactive
    - informative
---
