---
baseURL: "/"
languageCode: en-us
Title: Matúš Solčány
theme:
  - hugo-video
  - matussolcany
disableKinds:
  - "taxonomy"
  - "term"
  - "sitemap"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    Author: Matúš Solčány
    Description: Portfolio of digital designer Matúš Solčány
    SiteURL: "https://matussolcany.com"
    showcaseColumns: 2
    projectCategories:
    - interactive
    - visual
    - informative
---
